name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Install lib sunset
        run: pio lib -g install buelowp/sunset@1.1.3
      - name: Install lib adafruit RTClib
        run: pio lib -g install https://github.com/adafruit/RTClib/archive/refs/tags/2.0.3.zip
      - name: Install lib Adafruit NeoPixel
        run: pio lib -g install robtillaart/PCF8591
      - name: Install lib servo
        run: pio lib -g install arduino-libraries/Servo@1.1.8

      - name: Run PlatformIO
        run: pio run -e nanoatmega328

      - name: Install native
        run: pio platform install native
      - name: Run check
        run: pio check -e check
