name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest

      - name: Install lib adafruit RTClib
        run: pio lib -g install https://github.com/adafruit/RTClib/archive/refs/tags/2.0.3.zip
      - name: Install lib Adafruit NeoPixel
        run: pio lib -g install https://github.com/adafruit/Adafruit_NeoPixel/archive/refs/tags/1.10.5.zip
      - name: Install lib servo
        run: pio lib -g install arduino-libraries/Servo@1.1.8

      - name: Run PlatformIO
        run: pio run -e nanoatmega328

      - name: Install native
        run: pio platform install native
      - name: Run check
        run: pio check -e check

      - name: doxygen
        uses: mattnotmitt/doxygen-action@v1.9.2
